### ISSUE TITLE
Add append functionality

### ISSUE THREAD

**Issue by terrellt** [projecthydra-labs/activefedora-aggregation#22]

**Comment by jcoyne** [comment]
This should include the `<<` operator on `Association`

**Comment by flyingzumwalt** [comment]
FYI, you will probably need to do something like [ActiveFedora::Associations::Builder::HasMany](https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/associations/builder/has_many.rb), which is called when you call `has_many` (see [ActiveFedora::Associations::ClassMethods](https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/associations.rb#L104-L106)).  It follows the ActiveModel::Associations pattern.

This Builder adds the necessary methods to the target class and makes those methods return something like a [ActiveFedora::Associations::CollectionAssociation](https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/associations/collection_association.rb) instead of an Array.

Based on my experience with ActiveFedora, I *strongly recommend* simply doing this right, and following the ActiveModel::Associations pattern, up front.  If you don't it will bite you in the future.

**Comment by terrellt** [comment]
@flyingzumwalt This happens already, there's just no method to append since we had to create a new kind of association that deals with an IndirectContainer intermediary.

**Comment by terrellt** [comment]
@jcoyne told me not to do anything with this gem anymore, so I've been holding off here. Is that still accurate @jcoyne?

**Comment by flyingzumwalt** [comment]
:+1: figured you probably already had this covered, but wanted to make sure the info was there in case you didn't

**Comment by jcoyne** [comment]
@terrellt now that AF has IndirectContainers, the next step is to refactor AF-aggregation to use that. Then we can continue to march through the tickets.

**Comment by jcoyne** [comment]
```ruby
o1 = Hydra::PCDM::Object.new
=> #<Hydra::PCDM::Object id: nil, head_id: nil, tail_id: nil>
o2 = Hydra::PCDM::Object.new
=> #<Hydra::PCDM::Object id: nil, head_id: nil, tail_id: nil>
o1.members
=> []
o1.members << o2
=> [#<Hydra::PCDM::Object id: nil, head_id: nil, tail_id: nil>]
```

This works in the latest code.
