### ISSUE TITLE
Allow the root node for aggregations to be configurable

### ISSUE THREAD

**Issue by cam156** [projecthydra-labs/activefedora-aggregation#7]
Do the different objects live at the root node, or some other location down the tree.
Allow the location to be settable.

Should this really be ticketed here? Or should it be put in hydra-pdcm?

**Comment by elrayle** [comment]
Ex.
Configure collections to live under collections...  /collections/collection1
Configure generic works to live under generic_works...  /generic_works/generic_work1
Configure generic files to live under generic_files...  /generic_files/generic_file1
Configure binary files to live under files...  /generic_files/generic_file1/files/content.pdf

Another example we looked at has generic works and generic files all under /objects producing...
/objects/generic_work1
/objects/generic_file1

If this is configurable, then the app can decide on the preferred structure.

NOTE: Because a generic file can live in more than one generic work, it is stored as a sibling of generic_work.  Because a binary file can only live within one generic_file, it is stored as a child of the generic_file.

**Comment by jcoyne** [comment]
This ticket doesn't belong in this gem. It seems be be completed in https://github.com/projecthydra/active_fedora/pull/780
