### ISSUE TITLE
appending to Aggregation association always puts it in order

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/activefedora-aggregation#79]
presently there is no difference between:
```ruby
collection.members << object
collection.ordered_members << object 
```

**Comment by terrellt** [comment]
I'm working on this now, and I'd like to talk about what the APIs look like.

https://github.com/projecthydra-labs/activefedora-aggregation/blob/contained_ordering/spec/activefedora/ordered_spec.rb#L17-L44 That's what I've got so far. Questions I have:

1. What does deleting an object from the ordering look like? Because it can be in there multiple times. Maybe it doesn't make sense to delete an object? In that case, maybe it doesn't make sense to ADD an object either? There's an accessor for the proxies now, but maybe what really makes sense is an accessor for objects, and the main interaction mechanism being centered around the proxy.

2. What methods do we need? << is easy enough. I think we can get away with <<, #delete, and #insert_before.

**Comment by terrellt** [comment]
Another option I'm thinking of is for #ordered_members not returning the actual members, but a decorated object that contains which place in the ordering it is.

**Comment by terrellt** [comment]
Some potential options for removing: https://gist.github.com/terrellt/dd5ba658e0df5087e25f

**Comment by jcoyne** [comment]
I'm don't find the decorated option particularly appealing

**Comment by terrellt** [comment]
This spec works right now: https://gist.github.com/terrellt/619ac46e5193e284a3ba

**Comment by terrellt** [comment]
https://github.com/projecthydra-labs/activefedora-aggregation/compare/contained_ordering is getting dangerously close to a PR, and I'm interested in comments. Things I'm thinking of adding:

1. A convenience method for setting up the indirect container/ordering/list_source all at once.
2. Need some specs for how filtered associations work with this - or do we? Maybe just with the indirect association? #ordered_child_works/#ordered_file_sets seems problematic (and kind of impossible)
3. Need to get first/last put onto the owning object rather than on the list_source.
